### ISSUE TITLE
Print a more informative error message on failure

### ISSUE THREAD

**Issue by cooljeanius** [czyzby/wesnoth-png-optimizer#4]
I just tried adding this action to one of my repos, and got this result:
```
Cloning Wesnoth 1.16.10.
Cloning into '/wesnoth'...
fatal: 'utils/woptipng.py' is not a directory; to treat it as a directory anyway, rerun with --skip-checks
Wesnoth repository is ready.

Running woptipng with a threshold of 5...

Found unoptimized images above the optimization threshold.
See the logs from the woptipng tool.
```
IMO this output could stand to be improved. Perhaps it could say just how much above the optimization threshold the found images are, and what it might need to be set to instead? Also, when it says, "See the logs from the woptipng tool," I would find it helpful if it'd tell me where to look for them.

**Comment by czyzby** [comment]
`woptipng` used to log a lot of extra messages that were mostly irrelevant (i.e., the associated images were already optimized). You can see the current regular expression used to filter the messages as of writing this comment [here](https://github.com/czyzby/wesnoth-png-optimizer/blob/v1.2.0/entrypoint.sh#L23). It's possible that the Wesnoth tools were modified to include different messages, and as such either they are missed by the regular expression, or the way success is determined is no longer correct. I'll try to look into it after the holidays.

**Comment by czyzby** [comment]
The lack of logs was likely a red herring. The `woptipng` script might never have been executed in the first place due to the invalid sparse checkout issue (czyzby/wesnoth-wml-linter#7). I've pushed a fix for this into each Wesnoth actions repository and [tested it](https://github.com/czyzby/wesnoth-saurian-pack/actions/runs/7356609113/job/20027400171) with Wesnoth `1.16.11` in one of my repositories.

I see that you've added an image optimization bot, but I'd appreciate it if you added the action again and checked if it works as expected. In case any images have to be optimized, they should be printed in the `woptipng` logs.

**Comment by cooljeanius** [comment]
> I see that you've added an image optimization bot

Yeah, that's because I can't get `woptipng` to run locally for me due to matthiaskrgr/woptipng#2 and wesnoth/wesnoth#1988

> but I'd appreciate it if you added the action again and checked if it works as expected. In case any images have to be optimized, they should be printed in the `woptipng` logs.

I'd prefer to wait until the version number of the action has been incremented, as I mentioned in czyzby/wesnoth-wml-linter#7

**Comment by czyzby** [comment]
> I'd prefer to wait until the version number of the action has been incremented, as I mentioned in https://github.com/czyzby/wesnoth-wml-linter/issues/7

The version with the bugfix is `v1.2.1`. `latest` points to the main branch, while `v1` is continuously updated to point to the latest stable release. If you'd like to receive all bug fixes and new features without having to update the pipelines each time, `v1` is recommended. Any breaking changes would result in incrementing the major version, and the latest stable release would be available under `v2`. This is similar to how official actions are maintained, e.g. [`actions/checkout`](https://github.com/actions/checkout/tags).

**Comment by cooljeanius** [comment]
ok thanks, the new output is much better. It is kinda strange that `woptipng` and other image compression tools disagree about how much compression is possible, though...

**Comment by czyzby** [comment]
If I recall correctly, `woptipng` uses several tools to optimize the images, and then verifies the images at pixel level to make sure the compression is lossless. It's possible that some of them are more efficient that whatever that bot app is using.

By the way, it would be possible to add a GitHub Action that would work similar to the bot, although obviously less advanced. It would take a bit more effort to set up, since the users would have to generate an access token to make the commits possible. Handling protected branches would also be difficult with the simplest approach (i.e., without pull requests), but it should work fine for most basic Wesnoth mod repositories. I'm not actively modding Wesnoth anymore, but I could look into it if you think it would be worth the effort.

**Comment by cooljeanius** [comment]
> If I recall correctly, `woptipng` uses several tools to optimize the images, and then verifies the images at pixel level to make sure the compression is lossless. It's possible that some of them are more efficient that whatever that bot app is using.
> 
> By the way, it would be possible to add a GitHub Action that would work similar to the bot, although obviously less advanced. It would take a bit more effort to set up, since the users would have to generate an access token to make the commits possible. Handling protected branches would also be difficult with the simplest approach (i.e., without pull requests), but it should work fine for most basic Wesnoth mod repositories. I'm not actively modding Wesnoth anymore, but I could look into it if you think it would be worth the effort.

I mean... I guess there are a few separate possible paths forward here:

- You could modify this action to work more like @imgbot does
- @matthiaskrgr could fix matthiaskrgr/woptipng#2 so that I could run the tool locally
- I can just keep modifying the `threshold` value forever in each of my repos that uses this action to reflect whatever value it needs to be in each case

I don't really have a strong preference as to which of the 3 would be best. I'd be fine with any of them.

**Comment by czyzby** [comment]
@cooljeanius Turns out no changes were necessary, it's just that the commit has to be done as a separate pipeline step. This is an example of a workflow that uses latest Wesnoth version to optimize the images:

```yaml
name: optimize

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Optimize images
      uses: czyzby/wesnoth-png-optimizer@v1
      continue-on-error: true
      with:
        threshold: 0
    - name: Commit images
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@users.noreply.github.com"
        git commit -am "🤖 Optimize $GITHUB_REPOSITORY@$GITHUB_SHA"
        git push
```

And that's a similar one with a specific Wesnoth version:

```yaml
name: optimize

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  WESNOTH_VERSION: 1.16.11

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Optimize images
      uses: czyzby/wesnoth-png-optimizer@v1
      continue-on-error: true
      with:
        wesnoth-version: ${{ env.WESNOTH_VERSION }}
        threshold: 0
    - name: Commit images
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@users.noreply.github.com"
        git commit -am "🤖 Optimize $GITHUB_REPOSITORY@$GITHUB_SHA"
        git push
```

You can use that instead of the app bot, just make sure to adjust the branch names if necessary. I'd put it as a separate workflow (e.g., `optimize.yml`) next to the linters.
